### PR TITLE
feat: change deal's data_hash type to string

### PR DESCRIPTION
**Pull request by gyuguen**
## Implementation
* Add a command to delete protobuf to Makefile
* Change `data_hash`'s data type to string in `deal.proto`

## Description
The `data_hash` in panacea-core is a [string](https://github.com/medibloc/panacea-core/blob/main/proto/panacea/datadeal/v2/consent.proto#L27), but the `data_hash` in oracle is a byte array.

Conversions between byte arrays and strings in proto use Base64 encoding.(https://protobuf.dev/programming-guides/proto3/#json). However, we use dataHash in hexadecimals, so there is some confusion.

### CODE REVIEW

**Review by youngjoon-lee — APPROVED** [review]
lgtm!

**Review by H4NLee — APPROVED** [review]
lgtm
BTW, I think we can use base64 encoding for data hash. wdyt?

**Review by audtlr24 — APPROVED** [review]
Thanks. LGTM!

**Comment by gyuguen** [comment]
> lgtm BTW, I think we can use base64 encoding for data hash. wdyt?

Not a bad idea, but then our panacea-core's data_hash would have to be the same type.

**Comment by gyuguen** [comment]
If this is the case, I think we can unify the data_hash type of panacea-core and panacea-oracle to byte array.

**Comment by H4NLee** [comment]
> Not a bad idea, but then our panacea-core's data_hash would have to be the same type.
This is because they are both currently using hexadecimal.

In `panacea-core`, string type of `data_hash` is used without any decoding, so it looks good.
Anything is ok. I meant we can also use base64 encoding without modifying panacea-core side code :)

**Comment by gyuguen** [comment]
> > Not a bad idea, but then our panacea-core's data_hash would have to be the same type.
> > This is because they are both currently using hexadecimal.
> 
> In `panacea-core`, string type of `data_hash` is used without any decoding, so it looks good. Anything is ok. I meant we can also use base64 encoding without modifying panacea-core side code :)


Yes. It's a good way to go. One concern is that SHA256 hashing with common CLI tools results in hexadecimal encoding.
Probably not a big issue.

**Comment by gyuguen** [comment]
I'll think about it and if I decide it's okay, I'll create a new PR. :)

**Comment by H4NLee** [comment]
Ah, I see. It's not a big deal. Let's go as you did.

**Pull request merged**
