### PR TITLE
chore: add log when IPFS is not up

### PR DESCRIPTION
**Pull request by H4NLee**
Add log if IPFS is not up when oracle up

### CODE REVIEW

**Review by audtlr24 — APPROVED** [review]
Thanks, LGTM!

**Review by youngjoon-lee — COMMENTED** [review]
How about returning an error if IPFS isn't up? Of course, IFPS can be down later. But at least when we make the initial connection with IPFS, it's worth checking its liveness (as you did) and returning an error.

The reason why the following statement doesn't return an error is that the IPFS shell is HTTP-based which doesn't establish a permanent connection. But, if we decide to check its liveness this in this function, it also makes sense to return an error if it's not live.
```go
newShell := shell.NewShell(url)
```

**Comment by H4NLee** [comment]
> How about returning an error if IPFS isn't up? Of course, IFPS can be down later. But at least when we make the initial connection with IPFS, it's worth checking its liveness (as you did) and returning an error.

Actually, I thought about this. Ok. Let's check the liveness with an error when oracle daemon starts.

**Review by youngjoon-lee — APPROVED** [review]
lgtm

**Pull request merged**
