### PR TITLE
feat: add maxConnections and maxRequestBodySize limit setting.

### LINKED ISSUE #108: Added maxConnections and maxRequestBodySize limit setting.
## Background
If we don't limit the maximum number of connections on our server, we'll get a lot of requests, which will result in a lot of errors. In particular, our project is likely to experience OOM(Out of memory) due to SGX's memory limitations. Similarly, if we don't limit the size of the request body, we're likely to experience memory issues.

## Implementation
Add maxConnections and maxRequestBodySize to config.toml.

### PR DESCRIPTION
**Pull request by gyuguen**
close #108

### CODE REVIEW

**Comment by gyuguen** [comment]
I draft this PR because main branch is out of data.

**Comment by gyuguen** [comment]
This PR is ready!

**Review by youngjoon-lee — APPROVED** [review]
lgtm

**Review by audtlr24 — APPROVED** [review]
lgtm

**Pull request merged**
