### PR TITLE
ci: always pull panacea-core docker image 

### PR DESCRIPTION
**Pull request by youngjoon-lee**

### CODE REVIEW

**Review by audtlr24 — APPROVED** [review]
Thanks!

**Review by inchori — APPROVED** [review]
LGTM

**Comment by youngjoon-lee** [comment]
@audtlr24 @inchori sorry. i just fixed it again, pulling docker image in Makefile, instead of ci.yaml

**Review by audtlr24 — APPROVED** [review]
Okay, Thank you!

**Comment by gyuguen** [comment]
LGTM

I found that there are other ways to do it. But this code is good for now.

https://github.com/ory/dockertest/blob/v3/dockertest.go#L421

**Comment by youngjoon-lee** [comment]
> LGTM
> 
> I found that there are other ways to do it. But this code is good for now.
> 
> https://github.com/ory/dockertest/blob/v3/dockertest.go#L421

Cool. That is much nicer. Could you make a PR with that?

**Comment by gyuguen** [comment]
OK. I will open PR soon

**Pull request merged**
