### PR TITLE
feat: Add keepalive and change other settings

### PR DESCRIPTION
**Pull request by gyuguen**
Based on #86 

## Implement
* Change all time settings to `time.Duration`
* Add max concurrent streams configuration.
* Add max receive message size configuration.
* Add grpc keepalive configuration.

### CODE REVIEW

**Comment by gyuguen** [comment]
I haven't tested the keepalive configuration, but I think it will work.
I will run the test soon.

**Comment by gyuguen** [comment]
I have tested the above options and they all work fine.

**Review by youngjoon-lee — APPROVED** [review]
lgtm 👍

**Review by H4NLee — APPROVED** [review]
lgtm

**Review by audtlr24 — APPROVED** [review]
LGTM!

**Pull request merged**
