### PR TITLE
feat: change make file env GOBIN to GO

### PR DESCRIPTION
**Pull request by gyuguen**
When I run the `make install` command, the following error occurs.

```
> GOBIN=go make install
go install -mod=readonly -tags "" ./cmd/oracled
cannot install, GOBIN must be an absolute path
make: *** [install] Error 1
```

There is no problem with `GOBIN=go make build` or `GOBIN=go make test`.

It probably found the $GOBIN environment when running the `go install` command.

ref: https://pkg.go.dev/cmd/go
스크린샷 2022-06-07 오후 1 58 51

So, I changed environment `GOBIN` to `GO`

### CODE REVIEW

**Review by hansol-medi — COMMENTED** [review]
I also faced the same issue. Thank you for resolving this issue.
But you may also have to change `GOBIN` to `GO` in .github/workflows/ci.yaml. 👍

**Comment by gyuguen** [comment]
> fix

You're right. Thank you!
I changed it.(https://github.com/medibloc/panacea-oracle/pull/89/commits/3a62f573d7d2f83a97572920f08496c7d1f2c340)

**Comment by gyuguen** [comment]
> > I also faced the same issue. Thank you for resolving this issue. But you may also have to change `GOBIN` to `GO` in .github/workflows/ci.yaml. 👍
> 
> You're right. Thank you! I changed it.([3a62f57](https://github.com/medibloc/panacea-oracle/commit/3a62f573d7d2f83a97572920f08496c7d1f2c340))

CI is still failing, so I keep checking

**Comment by gyuguen** [comment]
> > > I also faced the same issue. Thank you for resolving this issue. But you may also have to change `GOBIN` to `GO` in .github/workflows/ci.yaml. 👍
> > 
> > 
> > You're right. Thank you! I changed it.([3a62f57](https://github.com/medibloc/panacea-oracle/commit/3a62f573d7d2f83a97572920f08496c7d1f2c340))
> 
> CI is still failing, so I keep checking

I fixed it. (https://github.com/medibloc/panacea-oracle/pull/89/commits/bde7802c990dea6ad826659e13e63b72bc522000)

In the e2e tests, there was a change in the order and the package name

**Review by hansol-medi — APPROVED** [review]
Thanks for fixing.
LGTM!

**Review by inchori — APPROVED** [review]
LGTM 👍

**Pull request merged**
