### PR TITLE
feat: merge branch release/v0.0.1 to main

### PR DESCRIPTION
**Pull request by gyuguen**
## Implementation
* Removed the schema from the `ListenAddr` of the GRPC/API server.
* Improved QueryHeight and JsonSchema logic.

### CODE REVIEW

**Review by youngjoon-lee — APPROVED** [review]
lgtm

**Review by audtlr24 — APPROVED** [review]
Thanks! lgtm

**Comment by gyuguen** [comment]
I draft this PR because it's not work now.

**Comment by gyuguen** [comment]
@youngjoon-lee @audtlr24 
Please review again. Fixed this commit.(https://github.com/medibloc/panacea-oracle/pull/112/commits/9df97ce4b7bfcad00800ab3e6e42d397c10d74b2)

**Review by audtlr24 — APPROVED** [review]
lgtm

**Pull request merged**
