### PR TITLE
feat: added data provider and JWT auth token issuer comparison

### LINKED ISSUE #65: Added a feature to verify that the data verification requester and the JWT token issuer is matched
When requesting data validation, we must verify that the provider_address in the request body matches the issuer of the JWT.

### PR DESCRIPTION
**Pull request by gyuguen**
close #65

### CODE REVIEW

**Review by H4NLee — APPROVED** [review]
Thank you I missed to add this.

**Review by youngjoon-lee — APPROVED** [review]
good. pls update the title of this PR like `.... and JWT auth token issuer ...`.

**Review by audtlr24 — APPROVED** [review]
lgtm

**Review by inchori — APPROVED** [review]
LGTM

**Pull request merged**
